
package webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelWebService", targetNamespace = "http://service.web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelWebService {


    /**
     * 
     * @return
     *     returns webservice.Adresse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdresse", targetNamespace = "http://service.web/", className = "webservice.GetAdresse")
    @ResponseWrapper(localName = "getAdresseResponse", targetNamespace = "http://service.web/", className = "webservice.GetAdresseResponse")
    @Action(input = "http://service.web/HotelWebService/getAdresseRequest", output = "http://service.web/HotelWebService/getAdresseResponse")
    public Adresse getAdresse();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "reserver", targetNamespace = "http://service.web/", className = "webservice.Reserver")
    @ResponseWrapper(localName = "reserverResponse", targetNamespace = "http://service.web/", className = "webservice.ReserverResponse")
    @Action(input = "http://service.web/HotelWebService/reserverRequest", output = "http://service.web/HotelWebService/reserverResponse")
    public void reserver(
        @WebParam(name = "arg0", targetNamespace = "")
        Client arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNom", targetNamespace = "http://service.web/", className = "webservice.GetNom")
    @ResponseWrapper(localName = "getNomResponse", targetNamespace = "http://service.web/", className = "webservice.GetNomResponse")
    @Action(input = "http://service.web/HotelWebService/getNomRequest", output = "http://service.web/HotelWebService/getNomResponse")
    public String getNom();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtoiles", targetNamespace = "http://service.web/", className = "webservice.GetEtoiles")
    @ResponseWrapper(localName = "getEtoilesResponse", targetNamespace = "http://service.web/", className = "webservice.GetEtoilesResponse")
    @Action(input = "http://service.web/HotelWebService/getEtoilesRequest", output = "http://service.web/HotelWebService/getEtoilesResponse")
    public int getEtoiles();

    /**
     * 
     * @return
     *     returns java.util.List<webservice.Chambre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getChambres", targetNamespace = "http://service.web/", className = "webservice.GetChambres")
    @ResponseWrapper(localName = "getChambresResponse", targetNamespace = "http://service.web/", className = "webservice.GetChambresResponse")
    @Action(input = "http://service.web/HotelWebService/getChambresRequest", output = "http://service.web/HotelWebService/getChambresResponse")
    public List<Chambre> getChambres();

}
